# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : minimal-mistakes-jekyll
# remote_theme           : "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : air # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Justin Rummel . com"
title_separator          : "-"
name                     : "Justin Rummel"
description              : 'Father, husband, Apple enthusiast.  üèä üö¥ üèÉ with <a href="https://www.instagram.com/explore/tags/speedsherpanation/">#speedsherpanation</a>, <a href="https://www.instagram.com/explore/tags/fxckcancertriteam/">#fxckcancertriteam</a>, and <a href="https://www.instagram.com/explore/tags/bikelaw/">#bikelaw</a>'
url                      : https://www.justinrummel.com
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : justinrummel/jr.com-mm # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : /assets/images/sierra-teaser.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2", "utterances", "custom"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "jr-branch"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  enabled                : true
  siteKey                :
  secret                 :
atom_feed:
  path                   : https://feeds.feedburner.com/jr # blank (default) uses feed.xml
search                   : true # false (default)
search_full_content      : false # true, false (default)
search_provider          : lunr # lunr (default), algolia
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

# SEO Related
google_site_verification : hT6wj0MiwnZDtC-APUPAkaE4cSidJtqaBCBq3Xnlnxk
bing_site_verification   : BF2EEED10A15A64DE29F3E540F77DC37
yandex_site_verification :
naver-site-verification  :

# Social Sharing
twitter:
  username               : "justinrummel"
facebook:
  username               : "justinrummel"
  app_id                 : "286537128062498"
  publisher              : "justinrummel"
og_image                 : # Open Graph/Twitter default site image
social:
  type                   : Person           # Person or Organization (defaults to Person)
  name                   : "Justin Rummel"  # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.facebook.com/justinrummel"
    - "https://github.com/justinrummel"
    - "https://www.instagram.com/justin.rummel/"
    - "https://www.linkedin.com/in/justinrummel"
    - "https://twitter.com/justinrummel"
    - "https://www.strava.com/athletes/justinrummel"

# Analytics
analytics:
  provider                : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id           : UA-41781912-1
    anonymize_ip          : # true, false (default)


# Site Author
author:
  name                    : "Justin Rummel"
  avatar                  : "https://www.gravatar.com/avatar/812849b04c44245ad29c0e40cb84e3da.jpg?s=110"
  bio                     : 'Father, husband, Apple enthusiast.  üèä üö¥ üèÉ with <a href="https://www.instagram.com/explore/tags/speedsherpanation/">#speedsherpanation</a>, <a href="https://www.instagram.com/explore/tags/fxckcancertriteam/">#fxckcancertriteam</a>, and <a href="https://www.instagram.com/explore/tags/bikelaw/">#bikelaw</a>'
  location                : False
  email                   : False
  url                     : "https://www.justinrummel.com/"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/justinrummel"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/justinrummel"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justinrummel"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/justin.rummel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justinrummel"
    - label: "Strava"
      icon: "fab fa-fw fa-strava orange"
      url: "https://www.strava.com/athletes/justinrummel"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/justinrummel"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/justinrummel"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justinrummel"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/justin.rummel"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justinrummel"
    - label: "Strava"
      icon: "fab fa-fw fa-strava"
      url: "https://www.strava.com/athletes/justinrummel"
    - label: "JSON"
      icon: "fab fa-fw fa-js-square"
      url: "/feed.json"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.gemspec"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - script
  - staticman.yml
  - tmp
  - vendor
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
encoding                  : "utf-8"
markdown_ext              : "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown                  : kramdown
highlighter               : rouge
lsi                       : false
future                    : false
show_drafts               : false
excerpt_separator         : "\n\n"
incremental               : false


# Markdown Processing
kramdown:
  hard_wrap               : false
  input                   : GFM
  auto_ids                : true
  auto_id_prefix          : 'jr_'
  footnote_nr             : 1
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  toc_levels              : 1..6
  enable_coderay          : false
  entity_output           : as_char


# Sass/SCSS
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# reCAPTCHA keys
reCaptcha:
  siteKey: "6Lfj9ysUAAAAAOWg3kjG9nsoDgJpZBo7PhxAMh1c"
  secret: "jlq9b/ZJ74mENEygF6jhYrTs/YUQVZoeMKl9giynbSXBmU5spAj1ETwwzaMOzsRqLukAEvAku5v5Af7O++2n2NGeSLQNOixSJfqCDrNMk3Ob6A4aRN11CQT5qFRlJxyVGmia8tZzqEyd1mrbZpd+AVsIh2sC5jhdrx+zgogCLkk="


# Outputting
permalink                 : /:title/
paginate                  : 5 # amount of posts to show
paginate_path             : /page:num/
timezone                  : America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <absolute_url>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <absolute_url/categories/my-awesome-category/index.html ~> path: /categories/
#  - <absolute_url/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false


# https://mmistakes.github.io/minimal-mistakes/docs/installation/
# Defaults
defaults:
  # _posts
  - scope:
      path                : ""
      type                : posts
    values:
      layout              : single
      author_profile      : true
      read_time           : false
      comments            : true
      share               : false
      related             : true
      sidebar:
        nav               : "docs"

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#head_scripts:
#  - /assets/js/your-custom-head-script.js
#footer_scripts:
#  - /assets/js/your-custom-head-script.js


# Default extensions when using octopress to generate new posts/pages
post_ext                  : md
page_ext                  : md
photos_ext                : md


# Found in _templates/
post_layout               : post
page_layout               : page
page_layout               : photos


# https://github.com/whaleen/jekyll-manifest.json
# Manifest settings (Used to make manifest.json)
# Edit manifest.json directly with icon information
manifest_name: Justin Rummel . com
manifest_short_name: JR.com # Appears in "Add to home screen" dialogues
manifest_lang: en-US
manifest_background_color: white
manifest_short_name:
manifest_display: standalone
